<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>NEW CASE REQUEST NOTIFICATION</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="css/style.css">

</head>
<style type="text/css">

</style>

<body>

    <body bgcolor="#f6f6f6" style="font-family: Arial; background-color: #f6f6f6;">

        <table border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" class="" style="width:62%;background-color:#fff;text-align:left;max-width:1024px;min-width:320px;margin:0 auto">
            <tbody>
                <tr>
                    <td>
                        <table border="0" cellspacing="0" cellpadding="0" height="8" background="" class="" style="width:100%;background-image:url();background-repeat:repeat-x;background-color:#43a4d0;height:8px">
                            <tbody>
                                <tr>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>

                        <table border="0" cellspacing="0" cellpadding="0" class="m_-8085786348450493519subscribe-header" style="width:100%;color:#08c;font-size:1.6em;background-color:#efefef;border-bottom:1px solid #ddd;margin:0;padding:0">
                            <tbody>
                                <tr  style="    height: 41px;">
                                    <td>
                                        <h2 class="" style="margin:.4em 0 .3em;font-size:1.8em;font-size:16px!important;line-height:1;font-weight:400;color:#464646;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;margin:5px 20px!important;padding:0">
														ITGS Verify - NEW CASE REQUEST NOTIFICATION  <small>{New case generated by client}</small>													</h2>
                                    </td>
                                    <td style="text-align:right">
                                        <img border="0" class="m_-8085786348450493519head-avatar CToWUd" src="" alt="" width="32" height="32" style="vertical-align:middle;margin:5px 20px 5px 0;vertical-align:middle">
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <table style="width:100%" border="0" cellspacing="0" cellpadding="20" bgcolor="#ffffff">
                            <tbody>
                                <tr>
                                    <td>
                                        <table style="width:100%" border="0" cellspacing="0" cellpadding="0">
                                            <tbody>
                                                <tr>
                                                    <td valign="top" class="m_-8085786348450493519the-post">
                                                        <table style="width:100%" border="0" cellspacing="0" cellpadding="0">
                                                            <tbody>
                                                                <tr>
                                                                    
                                                                    <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:4px;line-height:160%;padding:15px 0 15px;border-top:1px solid #eee;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">FROM : </a></strong> verify@itgsgroup.com </div>
                                                            <div class="m_-8085786348450493519meta" style="direction:ltr;color:#999;font-size:.9em;margin-top:-24px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">To : </a></strong> Respective Client Manager </div>
                                                            <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:-24px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">Subject :</a></strong> ITGS Verify - New Case Order <?php echo $data['client_reference'] ?> – <?php echo $data['reference_code'] ?>  </div>

                                                                    
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                            <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:-24px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">Message Details :</a></strong></div>
                                                            <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:-24px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <p style=" letter-spacing: 1px;     margin-top: 3px !important;   background-color: #dedede;     padding: 12px;
    border-radius: 7px;direction:ltr;font-size:14px;line-height:1.4em;color:#585757;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;margin:0 0 1em">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p></div>
                                                            
                                                        

                                                        <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:-31px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">A new case order has been generated.</a></strong> A new case order has been generated </div>
                                                             <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:-24px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">Client Reference Number : </a></strong> <?php echo $data['client_reference'] ?> </div>
                                                            <div class="" style="direction:ltr;color:#999;font-size:.9em;margin-top:-24px;line-height:160%;padding:15px 0 15px;overflow:hidden">
                                                            <strong><a style="text-decoration:underline;text-decoration: none;color:#2585b2" href="" target="" data-saferedirecturl="">ITGS Reference Number : </a></strong> <?php echo $data['reference_code'] ?> </div>

                                                        <p class="" style="direction:ltr;font-size:14px;line-height:1.4em;color:#444;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;margin:0 0 1em;font-size:14px;color:#666;padding:0;width:auto;padding-top:1em;padding-bottom:0em;margin-bottom:0;margin-left:0;padding-left:0">
                                                        </p>
                                                        
                                                        <p></p>
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <table border="0" cellspacing="0" cellpadding="20" bgcolor="#efefef" class="" style="width:100%;background-color:#e0dcdc;text-align:left;border-top:1px solid #ddd">
                            <tbody>
                                <tr>
                                    <td class="m_-8085786348450493519subscribe-content" style="border-top:1px solid #f3f3f3;color:#888;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;font-size:14px;background:#efefef">
                                        <p style="direction:ltr;font-size:14px;line-height:1.4em;color:#444;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;margin:0 0 1em;font-size:12px;line-height:1.4em;margin:0px 0px 10px 0px">
                                            <strong>Click on the link below to view details </strong> 
                                            <br> <a style="text-decoration:underline;color:#2585b2" href="<?php echo base_url('admin/form1/'.$data['case_id']) ?>" target="_blank" data-saferedirecturl="">Enter case link here</a></p>

                                        <p style="direction:ltr;font-size:14px;line-height:1.4em;color:#444;font-family:&quot;Helvetica Neue&quot;,Helvetica,Arial,sans-serif;margin:0 0 1em;font-size:12px;line-height:1.4em;margin:0px 0px 0px 0px">
                                            <strong>If you have any queries regarding this email. Please reach us on <a style="text-decoration:underline;color:#2585b2"  href="mailto:emailsupport@itgsgroup.com" target="_blank" data-saferedirecturl="">emailsupport@itgsgroup.com </a> OR contact us thorough our webpage</strong>  
                                            <br>
                                            <a style="text-decoration:underline;color:#2585b2" href="https://ingenioustribe.com/contact/" target="_blank" data-saferedirecturl="">https://ingenioustribe.com/contact/</a>
                                        </p>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <table border="0" cellspacing="0" cellpadding="0" height="8" background="" class="" style="width:100%;background-image:url();background-repeat:repeat-x;background-color:#43a4d0;height:8px">
                            <tbody>
                                <tr>
                                    <td></td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>

    </body>

</html>